### ISSUE TITLE
Update cache isn't fully working

### ISSUE THREAD

**Issue by travispavek** [travispavek/testrail-python#81]
The following methods don't work with UpdateCahce because they do not have a project_id or test_id.  I tried adding similar appropriate id checks but it didn't seem to work.
add_section
add_results
add_suite
add_case

For now I am flushing the cache when these methods are called.  @levi-rs to be honest I don't fully understand how the update works. Being you wrote it could you take a quick look and see if it is something obvious.

**Comment by levi-rs** [comment]
Sorry, I missed this earlier, I will look into it now.

**Comment by levi-rs** [comment]
I had to add some special logic to the API to make `add_result` work:
https://github.com/levi-rs/testrail-python/blob/master/testrail/api.py#L520-L525

@travispavek, the API needs to add something similar to the ones you mentioned above to make them work. How urgent is this? Im not sure I can dive into it today, but if you need it ASAP I'll see what I can do.

**Comment by travispavek** [comment]
@levi-rs not urgent at all.  The mentioned methods currently flush the cache so this isn't causing any bugs just a tad slower is all.  You get to it when you can, I appreciate your work on it!

**Comment by levi-rs** [comment]
Alright, I made a PR to update cache flushing for `add_results` and `add_suite`, both of which were pretty straight forward.

The other two, however, are going to be very tricky.

When adding a new section, the only required value is the project ID, but the response object doesn't have the project ID. This makes cache updating very challenging without completely rewriting the structure.

Likewise, adding a case only uses section ID, and I'm not entirely sure what the ramifications are if I go in and start switching the cache key from project ID to section ID.

I'm going to think about this some more, but I think the best approach for `add_section` and `add_case` might be to set those specific caches to flush, rather than setting the entire cache to flush.

**Comment by travispavek** [comment]
We can open a new issue if we come up with a way to cache add_[section,case].  For now PR #84 is sufficient.
